### ISSUE TITLE
TypeError: markdown() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by jarmitage** [munificent/craftinginterpreters#303]
Hi, I've installed the dependencies and attempted to `make` and got this output:

```
Traceback (most recent call last):
  File "util/build.py", line 542, in <module>
    format_files(False)
  File "util/build.py", line 492, in format_files
    format_file(file, skip_up_to_date, max(code_mod, templates_mod))
  File "util/build.py", line 384, in format_file
    body = markdown.markdown(contents, ['extra', 'codehilite', 'smarty'])
TypeError: markdown() takes 1 positional argument but 2 were given
make: *** [book] Error 1
```

Any idea what's happening?

**Comment by jarmitage** [comment]
Sorry just seen this is a dupe of #291
