### ISSUE TITLE
jlox NullPointerException on ctrl+d on Linux

### ISSUE THREAD

**Issue by ceronman** [munificent/craftinginterpreters#765]
If I try to exit the `jlox` REPL using the **ctrl d** key sequence, which is the normal sequence to end the terminal line input on Linux, I get a null pointer exception:

```
$ ./jlox
> print "hello world";
hello world
> Exception in thread "main" java.lang.NullPointerException
	at com.craftinginterpreters.lox.Scanner.isAtEnd(Scanner.java:219)
	at com.craftinginterpreters.lox.Scanner.scanTokens(Scanner.java:48)
	at com.craftinginterpreters.lox.Lox.run(Lox.java:64)
	at com.craftinginterpreters.lox.Lox.runPrompt(Lox.java:54)
	at com.craftinginterpreters.lox.Lox.main(Lox.java:30)
```

I tested this on Fedora Linux 32.
Using commit `67458314c0144eb782226c20103caddd8fa7a664` of this repository.

My java version is:

```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

**Comment by munificent** [comment]
Good catch, thank you!
